FROM python:3.9-slim

WORKDIR /app
COPY app/requirements.txt .
RUN pip install -r requirements.txt

COPY app/ .

USER root

ENV DEBUG=true
ENV API_KEY=hardcoded-api-key-value

CMD ["python", "main.py"]
