CREATE OR REPLACE VIEW `${GCP_PROJECT_ID}.${BQ_DATASET}.findings_summary_v` AS
SELECT
  finding_id,
  tool,
  category,
  subcategory,
  severity,
  confidence,
  title,
  description,
  rule_id,
  rule_name,
  file_path,
  line_start,
  line_end,
  resource_type,
  resource_name,
  package_name,
  vulnerability_id,
  repo,
  branch,
  commit_sha,
  pipeline_id,
  timestamp,
  DATE(timestamp) AS finding_date,
  status,
  environment,
  mitre_technique,
  CASE WHEN category = 'secret' THEN 1 ELSE 0 END AS is_secret,
  CASE WHEN severity = 'critical' THEN 1 ELSE 0 END AS is_critical,
  CASE WHEN severity = 'high' THEN 1 ELSE 0 END AS is_high
FROM `${GCP_PROJECT_ID}.${BQ_DATASET}.findings_normalized`;